### ISSUE TITLE
In the latest version of AutoMapper.Extensions.Microsoft.DependencyInjection (5.0.1), using Mapper.Map does not work

### ISSUE THREAD

**Issue by kubagdynia** [KevinDockx/BuildingAsyncAPIAspNetCore#1]
Using Mapper.Map does not work in the latest version of AutoMapper.Extensions.Microsoft.DependencyInjection

https://github.com/KevinDockx/BuildingAsyncAPIAspNetCore/blob/ad8977e9333aee3e03839a9cab198139e5534ee2/Finished%20sample/Books/Books.Api/Filters/BooksResultFilterAttribute.cs#L27

I found a solution that works for me, maybe it will help
https://github.com/AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection/issues/69

**Comment by KevinDockx** [comment]
The code uses v4, but in v5 a breaking change was introduced in regards to using the static Mapper combined with the depinj extension.  The fix Jimmy mentions in that link nicely solves this, thanks! :)
