### ISSUE TITLE
BooksResultFilterAttribute

### ISSUE THREAD

**Issue by johanbech** [KevinDockx/BuildingAsyncAPIAspNetCore#3]
Mapper.Map is not work what happen?

namespace Books.API.Filters
{
    public class BooksResultFilterAttribute : ResultFilterAttribute
    {
        public override async Task OnResultExecutionAsync(ResultExecutingContext context, ResultExecutionDelegate next)
        {

            var resultFRomAction = context.Result as ObjectResult;
            if (resultFRomAction?.Value == null || resultFRomAction.StatusCode < 200 || resultFRomAction.StatusCode >= 300)
            {
                await next();
                return;
            }
            resultFRomAction.Value = Mapper.Map<IEnumerable<Models.Book>>(resultFRomAction.Value);
            await next();
        }
    }
}

**Comment by KevinDockx** [comment]
Could it be you're using an Automapper version that's newer than the one in the course?  There were a few breaking changes with newer versions; from 8.x onwards it's better to inject an IMapper instance instead of using the static Mapper.

**Comment by johanbech** [comment]
oh i install newer version than in course. I try same as you use it´s working now.
Thanks.
